name: Default Workflow

on:
  push:
    branches-ignore:
      - main

jobs:
  ci:
    uses: amerani/cicd/.github/workflows/ci-npm.yml@main
    with:
      test: npm run test:ci
  cd:
    uses: amerani/cicd/.github/workflows/cd-npm.yml@main    
    with:
      test: npm run test:ci
      publish: npm run release
