name: Release Workflow

on:
  push:
    branches:
      - release

jobs:
  build:
    uses: ./.github/workflows/ci-build.yml
  release:
    uses: changesets/action@v1
    with:
      publish: npm run release
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

