name: Release Workflow

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: ./.github/workflows/ci-build.yml
      - name: Release
        uses: changesets/action@v1
        with:
          publish: npm run release
          setupGitUser: false
          commitMode: github-api
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

