name: Release Workflow

on:
  push:
    branches:
      - release

jobs:
  build:
    uses: ./.github/workflows/ci-build.yml
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: changesets/action@v1
        with:
          publish: npm run release
        secrets:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

